version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    container_name: 'flask-renee'
    volumes:
      - .:/application
    ports:
      - "1515:1515"
    networks:
      - app


networks:
  app:
    driver: bridge